substitutions:
  ip_address: 192.168.178.210
  device_name: "switch-entry"
  channel_1: "lights-hallway"
  channel_2: "lights-frontdoor"

  switch_name_1: "Lichtpunt hal"
  sensor_name_1: "Lichtknop hal"

  switch_name_2: "Lichtpunt voordeur"
  sensor_name_2: "Lichtknop voordeur"

  max_power: "2000.0"
  max_temp: "75.0"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: ${ip_address}
    gateway: 192.168.178.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name}-ap
    password: !secret hotspot_pass

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret esphome_api_password

# Enable OTA updates
ota:
  password: !secret esphome_api_password

# Enable Web server (optional).
web_server:
  port: 80

# Text sensors with general information.
text_sensor:
  - platform: version
    name: ${device_name}-esphome-version
  - platform: wifi_info
    ip_address:
      name: ${device_name}-ip-address

time:
  - platform: sntp
    id: my_time

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  # Sensors with general information.
  - platform: uptime
    name: ${device_name}-uptime
    entity_category: diagnostic

  - platform: wifi_signal
    name: ${device_name}-wifi-signal
    update_interval: 60s
    entity_category: diagnostic

  - platform: ade7953
    irq_pin: GPIO16 # Prevent overheating by setting this
    voltage:
      name: ${device_name}-voltage
    # On the Shelly 2.5 channels are mixed ch1=B ch2=A
    current_a:
      name: ${channel_2}-current
      internal: true
    current_b:
      name: ${channel_1}-current
      internal: true
    active_power_a:
      name: ${channel_2}-power
      id: power_sensor_2
      # active_power_a is normal, so don't multiply by -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: shelly_25_relay_2
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: ${switch_name_2} turned off because power exceeded ${max_power}W
    active_power_b:
      name: ${channel_1}-power
      id: power_sensor_1
      # active_power_b is inverted, so multiply by -1
      filters:
        - multiply: -1
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: shelly_25_relay_1
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: Message from ${device_name}
                data_template:
                  message: ${switch_name_1} turned off because power exceeded ${max_power}W
    update_interval: 30s

  - platform: total_daily_energy
    name: ${channel_1}-energy
    power_id: power_sensor_1
    filters:
      # Multiplication factor from W to kWh is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: total_daily_energy
    name: ${channel_2}-energy
    power_id: power_sensor_2
    filters:
      # Multiplication factor from W to kWh is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${device_name}-temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: shelly_25_relay_1
          - switch.turn_off: shelly_25_relay_2
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${device_name}
              data_template:
                message: Switches turned off because temperature exceeded ${max_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

switch:
  - platform: gpio
    id: shelly_25_relay_1
    name: ${switch_name_1}
    icon: mdi:lightning-bolt
    pin: GPIO4
  - platform: gpio
    id: shelly_25_relay_2
    name: ${switch_name_2}
    icon: mdi:lightning-bolt
    pin: GPIO15

binary_sensor:
  - platform: gpio
    id: shelly_input_1
    name: "${sensor_name_1}"
    pin:
      number: GPIO13
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
        then:
          - if:
              condition:
                and:
                  - wifi.connected:
                  - api.connected:
              then:
                # Do nothing, as the state of the binary sensor is already communicated
                # We let Home Assistant decide what to do with it
                - if:
                    condition:
                      switch.is_off: shelly_25_relay_1
                    then:
                      # If for some reason the connection was lost, the switch was turned off
                      # and the connection was re-established, turn the switch on again
                      - switch.turn_on: shelly_25_relay_1
              else:
                # else, toggle relay
                - switch.toggle: shelly_25_relay_1
  - platform: gpio
    id: shelly_input_2
    name: "${sensor_name_2}"
    pin:
      number: GPIO5
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
        then:
          # This switch does not control a smart light, but just a normal bulb, so just toggle relay
          # The state of the binary sensor is already communicated, so we can still use it in Home Assistant
          - switch.toggle: shelly_relay